NAME = SedIsForLoooser

FLAGS = -Wall -Wextra -Werror

all : $(NAME)

re : clean all

clean :
	@rm SedIsForLoooser
	@echo "SedIsForLoooser clear"

$(NAME) :
	@clang++ main.cpp Sed.hpp $(FLAGS)
	@mv a.out SedIsForLoooser
	@echo "SedIsForLoooser created"